### ISSUE TITLE
出现bad handshake: SysCallError(-1, 'Unexpected EOF')

### ISSUE THREAD

**Issue by Tarrence** [dixudx/tumblr-crawler#112]
出现如下错误是什么意思？   我在anaconda  python3.6  win10
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 299, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 150, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 163, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 167, in download_media
    self.download_videos(site)
  File "tumblr-photo-video-ripper.py", line 170, in download_videos
    self._download_media(site, "video", START)
  File "tumblr-photo-video-ripper.py", line 194, in _download_media
    proxies=self.proxies)
  File "C:\Users\renhl1\Anaconda3\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\renhl1\Anaconda3\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\renhl1\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\renhl1\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\renhl1\Anaconda3\lib\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

**Comment by dixudx** [comment]
@Tarrence 代理配置了吗
