### ISSUE TITLE
KeyError: '#text'错误

### ISSUE THREAD

**Issue by twbb** [dixudx/tumblr-crawler#2]
一开始都挺好，到1000多条的时候就会出KeyError: '#text'错误。
下面是显示的信息
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/root/tumblr-crawler/tumblr-photo-video-ripper.py", line 38, in run
    self.download(medium_type, post, target_folder)
  File "/root/tumblr-crawler/tumblr-photo-video-ripper.py", line 43, in download
    medium_url = self._handle_medium_url(medium_type, post)
  File "/root/tumblr-crawler/tumblr-photo-video-ripper.py", line 53, in _handle_medium_url
    video_player = post["video-player"][1]["#text"]
KeyError: '#text'

**Comment by dixudx** [comment]
Already add an exception handler for these unknown source formats. Refer to [commit abcc178](https://github.com/dixudx/tumblr-crawler/commit/abcc1781249f8bb230a8f0ba9026ebc72903305f).

Try to pull latest code and try again. And this crawler will not re-download the images and videos. Don't worry and you won't miss anything.

Also would you please provide the detailed exception log, so that I can add this new video source.

Actually you will see 

```
TypeError:

Unable to find the right url for downloading. Please open a new issue on https://github.com/dixudx/tumblr-crawler/issues/new attached with below information


xxxxxxxxxxxxx
```
