### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by Jarvay** [dixudx/tumblr-crawler#20]
用的是shadowsocks,用浏览器能访问tumblr,代理是按教程填写的，但是打开后过了一分钟左右出现这个异常，请问怎么解决。。

**Comment by dixudx** [comment]
能否把异常贴出来

**Comment by Jarvay** [comment]
@dixudx 
`You are using proxies.
{u'http': u'socks5://127.0.0.1:1080', u'https': u'socks5://127.0.0.1:1080'}
Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 284, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 150, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 163, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 166, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 177, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 194, in _download_media
    proxies=self.proxies)
  File "D:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python27\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))`

**Comment by Jarvay** [comment]
@dixudx 
You are using proxies.
{u'http': u'socks5://127.0.0.1:1080', u'https': u'socks5://127.0.0.1:1080'}
Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 284, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 150, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 163, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 166, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 177, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 194, in _download_media
    proxies=self.proxies)
  File "D:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python27\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by dixudx** [comment]
Shadowsocks is running in `Global Mode` ?

If so, you may leave file `proxies.json` empty on Windows. Just have another try.

**Comment by Jarvay** [comment]
是全局的，代理为空还是不行。。

**Comment by dixudx** [comment]
代理稳定吗？

**Comment by Jarvay** [comment]
不知道是不是因为代理不稳定，但是我用站点作为命令参数的方式行了，之前是写在sites里面的
不管怎样还是行了，谢谢
