### ISSUE TITLE
运行脚本错误；shadowsocks 全局代理确定没有问题的

### ISSUE THREAD

**Issue by fxd2006** [dixudx/tumblr-crawler#29]
D:\python\tumblr-crawler-master>python tumblr-photo-video-ripper.py
You are using proxies.
{'http': 'socks5://127.0.0.1:1080', 'https': 'socks5://127.0.0.1:1080'}
Traceback (most recent call last):
  File "D:\python\lib\site-packages\requests\packages\urllib3\connectionpool.py"
, line 600, in urlopen
    chunked=chunked)
  File "D:\python\lib\site-packages\requests\packages\urllib3\connectionpool.py"
, line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\python\lib\site-packages\requests\packages\urllib3\connectionpool.py"
, line 382, in _make_request
    httplib_response = conn.getresponse()
  File "D:\python\lib\http\client.py", line 1197, in getresponse
    response.begin()
  File "D:\python\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "D:\python\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "D:\python\lib\site-packages\requests\packages\urllib3\connectionpool.py"
, line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\python\lib\site-packages\requests\packages\urllib3\util\retry.py", li
ne 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\python\lib\site-packages\requests\packages\urllib3\packages\six.py",
line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\python\lib\site-packages\requests\packages\urllib3\connectionpool.py"
, line 600, in urlopen
    chunked=chunked)
  File "D:\python\lib\site-packages\requests\packages\urllib3\connectionpool.py"
, line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\python\lib\site-packages\requests\packages\urllib3\connectionpool.py"
, line 382, in _make_request
    httplib_response = conn.getresponse()
  File "D:\python\lib\http\client.py", line 1197, in getresponse
    response.begin()
  File "D:\python\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "D:\python\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', Remo
teDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 288, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 165, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 193, in _download_media
    proxies=self.proxies)
  File "D:\python\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "D:\python\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected(
'Remote end closed connection without response',))

D:\python\tumblr-crawler-master>

**Comment by dixudx** [comment]
1. Make sure that you're using latest codes, using `git pull` to get latest codes;
2. Is your proxy stable enough? Please retry again.
