### ISSUE TITLE
an error when downloading videos

### ISSUE THREAD

**Issue by colorblank** [dixudx/tumblr-crawler#30]
here is the error feedback:
>
Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 288, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 165, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 193, in _download_media
    proxies=self.proxies)
  File "/Users/zhang/anaconda/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/zhang/anaconda/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/zhang/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/zhang/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/zhang/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 190, in resolve_redirects
    **adapter_kwargs
  File "/Users/zhang/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/zhang/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
>
I have no idea about what's happening.I hope you can help.
Thank you!

**Comment by dixudx** [comment]
`BadStatusLine` is an exception coming out of the bowels of `httplib`, and it suggests that the data it receives doesn't make any sense. In this case, it's because it detects that you're trying to scrape it and deliberately disconnecting you.

You can take below checks and retry:
1. Is your proxy stable? Can you visit the website using browser?;
2. Modify `TIMEOUT` in [tumblr-photo-video-ripper.py#L13](https://github.com/dixudx/tumblr-crawler/blob/master/tumblr-photo-video-ripper.py#L13) to a larger value;

**Comment by colorblank** [comment]
1.I can visit the tumblr easily by using the browser.；
but some blogs of the tumblr can not  be downloaded, some can download a few photos, but not all.

2.No matter how to adjust the value of TIMEOUT, in a few minutes ,it will stop and return with this error.
And sometimes it will run without an error in a long time.

**Comment by colorblank** [comment]
I use the IPSEC VPN.DO I need use the proxy?

**Comment by dixudx** [comment]
@colorblank  This seems to relate to your proxy. You may not set ipsec vpn info to `proxy.json`.

You proxy is not stable enough. Please retry it when such error occurs.
