### ISSUE TITLE
ERROR when downloading tumblr

### ISSUE THREAD

**Issue by Yodamt** [dixudx/tumblr-crawler#31]
I 'm using shadowsocksr with socks5 through 127.0.0.1:10323
When running the scripts,it appears to be the following :

`You are using proxies.
{'http': 'socks5://127.0.0.1:10323', 'https': 'socks5://127.0.0.1:10323'}
Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 227, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 127, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 141, in scheduling
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 153, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 170, in _download_media
    data = xmltodict.parse(response.content)
  File "C:\Users\jdds1\AppData\Local\Programs\Python\Python36\lib\site-packages\xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 28, column 41`

I have no idea what happened, and I 've ensured that my proxy is stable 'cause the target website can be visited by my browser.
Hoping for replying soon

**Comment by dixudx** [comment]
@Yodamt It seems that the response content can not be well parsed. Have you pulled the latest code?

Also I wonder whether this site needs login. If possible, would you mind sending me this site url.

**Comment by Yodamt** [comment]
I just clone ur code on github whick I thought be the latest.
Here is the url  `https://sexisxing.tumblr.com/`
while occurs to the "xml not well-formed" probem,I restart the script then it can crawl some more pics.
But the problem comes again soon... Sounds like a terrible loop :(
When reviewing the pics downloaded , I found that some pic's part got broken and show a mixture of it's part and Meaningless image.

**Comment by Yodamt** [comment]
Here is the URL:`https://sexisxing.tumblr.com/`
And the problem is about the token(session id?) 
Just guessing:)

**Comment by Yodamt** [comment]
I 've cloned the master-branch code on github.
Here is the URL:`https://sexisxing.tumblr.com/`
And the problem is about the token(session id?) 
Just guessing:)

**Comment by dixudx** [comment]
@Yodamt Got it

**Comment by dixudx** [comment]
@Yodamt I've already find the bug. The return xml is invalid, which contains invalid character.

You can override this error by setting [`MEDIA_NUM`](https://github.com/dixudx/tumblr-crawler/blob/master/tumblr-photo-video-ripper.py#L23) to a larger value, for example 100. Works well on my machine.

**Comment by Yodamt** [comment]
Thanks.trick worrks!:)

**Comment by Yodamt** [comment]
BTW,can this scripts improved to crawl 4chan 's board?
:)

**Comment by Yodamt** [comment]
New problem
`E:\下载\tumblrshit\tumblr-crawler-master_dixudx\tumblr-crawler-master>python tumblr-photo-video-ripper.py
You are using proxies.
{'http': 'socks5://127.0.0.1:10103', 'https': 'socks5://127.0.0.1:10103'}
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 288, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 165, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 193, in _download_media
    proxies=self.proxies)
  File "C:\Python36\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python36\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: 
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
`
Seems cnnot load any url
And the sites can be visited through the browser with no problem

**Comment by dixudx** [comment]
@Yodamt It seems that the proxy is not stable enough. Please retry.

This exception is raised due to the fact that the server closes our connection after we've sent the request but before responding. As the Tumblr server is actually more stable than our proxy. I guess the more likely root cause is the proxy.

You can try to restart your proxy or retry running the script.
