### ISSUE TITLE
图片都下来了 视频没有

### ISSUE THREAD

**Issue by real3841** [dixudx/tumblr-crawler#36]
Downloading tumblr_oq86meTiUR1w2sarao5_250.jpg from https://68.media.tumblr.com/3fa3f7c2ad890e3a0a20e3aa95fb77da/tumblr_oq86meTiUR1w2sarao5_250.jpg.

Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 288, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 165, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 199, in _download_media
    data = xmltodict.parse(response.content)
  File "/usr/local/lib/python3.5/site-packages/xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 19, column 4010
➜  tumblr-crawler git:(master) ✗

**Comment by dixudx** [comment]
@real3841 Sorry for the late reply. Have you used the latest code? It seems that you're requesting a private blog that needs login/authentication.

**Comment by real3841** [comment]
hi Dixudx,

no. i have try many blog, but all of them are same.

**Comment by dixudx** [comment]
@real3841 Have you enabled the proxy? Any detailed log?
