### ISSUE TITLE
Downloading videos sometimes does not work

### ISSUE THREAD

**Issue by haocwang** [dixudx/tumblr-crawler#39]
Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 288, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 166, in download_media
    self.download_videos(site)
  File "tumblr-photo-video-ripper.py", line 169, in download_videos
    self._download_media(site, "video", START)
  File "tumblr-photo-video-ripper.py", line 199, in _download_media
    data = xmltodict.parse(response.content)
  File "/Library/Python/2.7/site-packages/xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 87: unexpected end of data

**Comment by dixudx** [comment]
@haocwang The site you want to download from contains non-decoded characters. This is not a bug of this crawler. You can try to download another site.

**Comment by Sweeeeety** [comment]
Wouldn't it be much better to catch this error and handle it proberly instead of letting the application crash?
Could this be done easily?

BR

Sweeeeety

**Comment by dixudx** [comment]
@haocwang @Sweeeeety Fixed. Please pull the latest code.
