### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by gwjczwy** [dixudx/tumblr-crawler#41]
莫名奇妙就报错了。
而且还成功过。一共成功过两次，第二次只下载了sites.txt里的第一个人的，随后就不能下载了。
错误代码：

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 438, in wrap_socket
    cnx.do_handshake()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1638, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1378, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 445, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\adapters.py", line 438, in send
    timeout=timeout
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 288, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 165, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 193, in _download_media
    proxies=self.proxies)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 661, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 661, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 214, in resolve_redirects
    **adapter_kwargs
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\adapters.py", line 512, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

C:\Users\Administrator\1>python tumblr-photo-video-ripper.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 438, in wrap_socket
    cnx.do_handshake()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1638, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1378, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 445, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\adapters.py", line 438, in send
    timeout=timeout
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 288, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 165, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 193, in _download_media
    proxies=self.proxies)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 661, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 661, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 214, in resolve_redirects
    **adapter_kwargs
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\adapters.py", line 512, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by dixudx** [comment]
@gwjczwy This has nothing to do with the crawler. All the logs show that the root cause is your proxy. Please check whether your proxy is usable and stable.

> OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]
