### ISSUE TITLE
运行一下子就报错退出了，重新运行也是如此

### ISSUE THREAD

**Issue by i0668** [dixudx/tumblr-crawler#48]
```
Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 291, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 166, in download_media
    self.download_videos(site)
  File "tumblr-photo-video-ripper.py", line 169, in download_videos
    self._download_media(site, "video", START)
  File "tumblr-photo-video-ripper.py", line 199, in _download_media
    data = xmltodict.parse(response.content)
  File "/usr/lib/python2.7/site-packages/xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 480, column 1496
```

**Comment by dixudx** [comment]
@zlfzy Refer to #33.

**Comment by i0668** [comment]
@dixudx thanks
