### ISSUE TITLE
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'remove'

### ISSUE THREAD

**Issue by 1a57danc3** [dixudx/tumblr-crawler#52]
Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 291, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 165, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 199, in _download_media
    data = xmltodict.parse(response.content)
  File "/usr/lib/python2.7/dist-packages/xmltodict.py", line 248, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 11, column 2289
Downloading tumblr_nidkcnIqFf1tbp9pfo8_1280.jpg from http://xxxxxxxx/tumblr_nidkcnIqFf1tbp9pfo8_1280.jpg.

Downloading tumblr_nidkcnIqFf1tbp9pfo9_1280.jpg from http://xxxxxxxxxx/tumblr_nidkcnIqFf1tbp9pfo9_1280.jpg.

Exception in thread Thread-2 (most likely raised during interpreter shutdown):Exception in thread Thread-1 (most likely raised during interpreter shutdown):Exception in thread Thread-7 (most likely raised during interpreter shutdown):

Traceback (most recent call last):
Traceback (most recent call last):  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "tumblr-photo-video-ripper.py", line 65, in run

  File "tumblr-photo-video-ripper.py", line 65, in run  File "tumblr-photo-video-ripper.py", line 72, in download

  File "tumblr-photo-video-ripper.py", line 136, in _download  File "tumblr-photo-video-ripper.py", line 72, in download

  File "tumblr-photo-video-ripper.py", line 136, in _download<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'remove'

Traceback (most recent call last):
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'remove'
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

  File "tumblr-photo-video-ripper.py", line 65, in run
  File "tumblr-photo-video-ripper.py", line 72, in download
  File "tumblr-photo-video-ripper.py", line 136, in _download
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'remove'
 Exception in thread Thread-6 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "tumblr-photo-video-ripper.py", line 65, in run
  File "tumblr-photo-video-ripper.py", line 72, in download
  File "tumblr-photo-video-ripper.py", line 136, in _download
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'remove'

No proxy setting, have some problems witg XML decode?

**Comment by 1a57danc3** [comment]
If run again

Traceback (most recent call last):
  File "tumblr-photo-video-ripper.py", line 291, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tumblr-photo-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "tumblr-photo-video-ripper.py", line 162, in scheduling
    self.download_media(site)
  File "tumblr-photo-video-ripper.py", line 165, in download_media
    self.download_photos(site)
  File "tumblr-photo-video-ripper.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tumblr-photo-video-ripper.py", line 199, in _download_media
    data = xmltodict.parse(response.content)
  File "/usr/lib/python2.7/dist-packages/xmltodict.py", line 248, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 11, column 2289

**Comment by dixudx** [comment]
@ky0ncheng Please refer to #33 and #31.
