### ISSUE TITLE
视频图片下载中断

### ISSUE THREAD

**Issue by AdolfFrederichK** [dixudx/tumblr-crawler#80]
每次都下载不完全，然后报这个错。

Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "tumblr-photo-video-ripper.py", line 64, in run
  File "/usr/local/lib/python2.7/Queue.py", line 168, in get
  File "/usr/local/lib/python2.7/threading.py", line 333, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

这是什么问题呢

**Comment by dixudx** [comment]
@AdolfFrederichK Any detailed logs?
