### ISSUE TITLE
what's wrong with this?

### ISSUE THREAD

**Issue by minxingtu** [dixudx/tumblr-crawler#82]
requests.exceptions.ConnectionError: ('Connection aborted.', UnknownProtocol('HTTP/2.0'))

**Comment by dixudx** [comment]
@minxingtu Never met such exception.

Seems to be related with `requests`. You can try to upgrade `requests` by `pip install -U requests`.

**Comment by minxingtu** [comment]
unfortunately, that doesn't work.

**Comment by minxingtu** [comment]
Traceback (most recent call last):
  File "tm.py", line 298, in <module>
    CrawlerScheduler(sites, proxies=proxies)
  File "tm.py", line 149, in __init__
    self.scheduling()
  File "tm.py", line 162, in scheduling
    self.download_media(site)
  File "tm.py", line 165, in download_media
    self.download_photos(site)
  File "tm.py", line 176, in download_photos
    self._download_media(site, "photo", START)
  File "tm.py", line 193, in _download_media
    proxies=self.proxies)
  File "D:\python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "D:\python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\python27\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', UnknownProtocol('HTTP/2.0',))

**Comment by dixudx** [comment]
@minxingtu How is your proxy setting?

**Comment by minxingtu** [comment]
I think I don't use proxies.
